name: Create Dependency Snapshot

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run this workflow on'
        required: false
        default: development


jobs:
  submit-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Generate and submit dependency snapshot
        run: |
          node -e "
            (async () => {
              const { PackageCache, Snapshot } = require('@github/dependency-submission-toolkit');
              const { readFileSync } = require('fs');
              const { join } = require('path');

              const packageJsonPath = join(process.cwd(), 'package.json');
              const lockFilePath = join(process.cwd(), 'package-lock.json');

              const packageJson = JSON.parse(readFileSync(packageJsonPath));

              let dependencies = {};
              try {
                const lockData = JSON.parse(readFileSync(lockFilePath));
                if (lockData.dependencies) {
                  Object.keys(lockData.dependencies).forEach(dep => {
                    dependencies[dep] = lockData.dependencies[dep].version;
                  });
                }
              } catch (err) {
                console.warn('No valid package-lock.json found, using package.json dependencies');
                if (packageJson.dependencies) {
                  dependencies = { ...packageJson.dependencies };
                }
              }

              const packageCache = new PackageCache();
              packageCache.addPackage({
                name: packageJson.name,
                version: packageJson.version,
                dependencies
              });

              const snapshot = new Snapshot({
                correlator: '${{ github.workflow }}-${{ github.job }}',
                commitSha: '${{ github.sha }}',
                detector: { name: 'custom-detector' },
                manifests: [],
                buildTargets: [],
              });

              await snapshot.submit();
              console.log('Dependency snapshot submitted successfully!');
            })();
          "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}