name: NPM Dependency Submission

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to submit dependencies for"
        required: false
        default: "main"

permissions:
  contents: write          # required for actions/checkout
  id-token: write          # required for dependency submission
  security-events: write   # required for dependency submission

jobs:
  submit-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Submit dependency snapshot
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.0
