name: Component Detection

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to run component detection on'
        required: true
        default: "development"

permissions:
  contents: write          # required for actions/checkout
  id-token: write          # required for dependency submission
  security-events: write   # required for dependency submission

jobs:
  detect-components:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: sbt/setup-sbt@v1
      - uses: scalacenter/sbt-dependency-submission@v2