name: Submit Dependency Snapshot

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to submit snapshot for'
        required: false
        default: ''
      sha:
        description: 'Commit SHA to submit snapshot for'
        required: false
        default: ''

permissions:
  contents: write          # required for actions/checkout
  id-token: write          # required for dependency submission
  security-events: write   # required for dependency submission

jobs:
  submit-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
    
      - name: Request Deployment
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.event.inputs.branch || github.ref_name }}
          COMMIT_SHA: ${{ github.event.inputs.sha || github.sha }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.rest.dependencyGraph.createRepositorySnapshot({
              owner: process.env.GITHUB_REPOSITORY.split('/')[0],
              repo: process.env.GITHUB_REPOSITORY.split('/')[1],
              version: 0,
              sha: process.env.COMMIT_SHA,
              ref: `refs/heads/${process.env.BRANCH_NAME}`,
              job: {
                correlator: `${process.env.GITHUB_WORKFLOW}_${process.env.GITHUB_JOB}`,
                id: process.env.GITHUB_RUN_ID
              },
              detector: {
                name: 'octo-detector',
                version: '0.0.1',
                url: 'https://github.com/octo-org/octo-repo'
              },
              scanned: new Date().toISOString(),
              manifests: {
                'package-lock.json': {
                  name: 'package-lock.json',
                  file: { source_location: 'package-lock.json' },
                }
              },
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
            console.log('Dependency snapshot submitted successfully!');
