name: Submit Dependency Snapshot

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to submit snapshot for'
        required: false
        default: ''
      sha:
        description: 'Commit SHA to submit snapshot for'
        required: false
        default: ''

jobs:
  submit-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Read package-lock.json and construct snapshot
        id: snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.event.inputs.branch || github.ref_name }}
          COMMIT_SHA: ${{ github.event.inputs.sha || github.sha }}
        run: |
            await github.rest.dependencyGraph.createRepositorySnapshot({ 
                owner: process.env.GITHUB_REPOSITORY.split('/')[0],
                repo: process.env.GITHUB_REPOSITORY.split('/')[1],
                version: 0,
                sha: process.env.GITHUB_SHA,
                ref: `refs/heads/${process.env.GITHUB_REF_NAME}`,
                job: {
                    correlator: `${process.env.GITHUB_WORKFLOW}_${process.env.GITHUB_JOB}`,
                    id: process.env.GITHUB_RUN_ID
                },
                detector: {
                    name: 'octo-detector',
                    version: '0.0.1',
                    url: 'https://github.com/octo-org/octo-repo'
                },
                scanned: '2022-06-14T20:25:00Z',
                manifests: {
                    'package-lock.json': {
                        name: 'package-lock.json',
                    }
                },
                headers: {
                    'X-GitHub-Api-Version': '2022-11-28'
                }
            })