name: Submit Dependency Snapshot

on:
  push:
    branches:
      - main
      - 'release/*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run this workflow on'
        required: false
        default: main

jobs:
  submit-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Read package-lock.json and construct snapshot
        id: snapshot
        run: |
          node -e "
            const { readFileSync } = require('fs');
            const { join } = require('path');

            const lockPath = join(process.cwd(), 'package-lock.json');
            const lockData = JSON.parse(readFileSync(lockPath));

            const manifests = {};
            manifests['package-lock.json'] = {
              name: 'package-lock.json',
              file: { source_location: 'package-lock.json' },
              resolved: {}
            };

            if (lockData.dependencies) {
              Object.entries(lockData.dependencies).forEach(([pkg, info]) => {
                manifests['package-lock.json'].resolved[pkg] = {
                  package_url: `pkg:/npm/${encodeURIComponent(pkg)}@${info.version}`,
                  dependencies: info.requires ? Object.keys(info.requires) : []
                };
              });
            }

            // Save JSON for curl
            const snapshot = {
              version: 0,
              sha: process.env.GITHUB_SHA,
              ref: `refs/heads/${process.env.GITHUB_REF_NAME}`,
              job: {
                correlator: `${process.env.GITHUB_WORKFLOW}_${process.env.GITHUB_JOB}`,
                id: process.env.GITHUB_RUN_ID
              },
              detector: {
                name: 'octo-detector',
                version: '0.0.1',
                url: 'https://github.com/octo-org/octo-repo'
              },
              scanned: new Date().toISOString(),
              manifests
            };

            require('fs').writeFileSync('snapshot.json', JSON.stringify(snapshot, null, 2));
          "
      
      - name: Submit snapshot to GitHub Dependency Graph
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/dependency-graph/snapshots \
            -d @snapshot.json
