name: 'Dependency Review'
on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'The commit ref or SHA'
        required: true
        default: 'main'

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          warn-only: true
          head-ref: ${{ github.event.inputs.sha }}