name: Component Detection

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to run component detection on'
        required: true
        default: 'development'

jobs:
  detect-components:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Run Component Detection Submission
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
